name: Compile C Code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install build dependencies
      run: sudo apt-get install -y build-essential

    - name: Compile C code
      run: gcc -o server main_linux.c

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        commit_message: Publish compiled binary
